/*
 * APS
 *
 * (C) Copyright 2015-2017 Vladimir Grechka
 *
 * YOU DON'T MESS AROUND WITH THIS SHIT, IT WAS GENERATED BY A TOOL SMARTER THAN YOU
 */

package aps

import aps.*

@Generated @Ser class MirandaImposeNextGeneratedPassword(val password: String)
@Generated @Ser class MirandaImposeNextGeneratedUserToken(val token: String)
@Generated @Ser class MirandaImposeNextOrderID(val id: Long)
