/*
 * APS
 *
 * (C) Copyright 2015-2017 Vladimir Grechka
 *
 * YOU DON'T MESS AROUND WITH THIS SHIT, IT WAS GENERATED BY A TOOL SMARTER THAN YOU
 */

package aps

import aps.*


// ==================================================================
// REMOTE PROCEDURE TOS
// ==================================================================

@Generated @Ser class __MirandaImposeNextGeneratedPassword(val password: String)
@Generated class __MirandaImposeNextGeneratedPassword_Response(override val value: Unit) : CommonResponseFieldsImpl(), SingleValueResponse<Unit>
@Generated @Ser class __MirandaImposeNextGeneratedUserToken(val token: String)
@Generated class __MirandaImposeNextGeneratedUserToken_Response(override val value: Unit) : CommonResponseFieldsImpl(), SingleValueResponse<Unit>
@Generated @Ser class __MirandaImposeNextOrderID(val id: Long)
@Generated class __MirandaImposeNextOrderID_Response(override val value: Unit) : CommonResponseFieldsImpl(), SingleValueResponse<Unit>
@Generated @Ser class __MirandaGetGeneratedTestTimestamps()
@Generated class __MirandaGetGeneratedTestTimestamps_Response(override val value: List<String>) : CommonResponseFieldsImpl(), SingleValueResponse<List<String>>
@Generated @Ser class __MirandaSeedSomeStuff1()
@Generated class __MirandaSeedSomeStuff1_Response(override val value: Unit) : CommonResponseFieldsImpl(), SingleValueResponse<Unit>
@Generated @Ser class __ReginaAdminSendOrderToStore(val orderID: Long)
@Generated class __ReginaAdminSendOrderToStore_Response(override val value: Unit) : CommonResponseFieldsImpl(), SingleValueResponse<Unit>
