/*
 * APS
 *
 * (C) Copyright 2015-2017 Vladimir Grechka
 *
 * YOU DON'T MESS AROUND WITH THIS SHIT, IT WAS GENERATED BY A TOOL SMARTER THAN YOU
 */

package aps.front

import aps.*

@Generated suspend fun mirandaImposeNextGeneratedPassword(password:String): GenericResponse = _askMiranda(MirandaImposeNextGeneratedPassword(password = password))
@Generated suspend fun mirandaImposeNextGeneratedUserToken(token:String): GenericResponse = _askMiranda(MirandaImposeNextGeneratedUserToken(token = token))
@Generated suspend fun mirandaImposeNextOrderID(id:Long): GenericResponse = _askMiranda(MirandaImposeNextOrderID(id = id))
