/*
 * APS
 *
 * (C) Copyright 2015-2017 Vladimir Grechka
 *
 * YOU DON'T MESS AROUND WITH THIS SHIT, IT WAS GENERATED BY A TOOL SMARTER THAN YOU
 */

package aps.front

import aps.*

@Generated suspend fun mirandaImposeNextGeneratedPassword(password:String): Unit = _askMiranda<MirandaImposeNextGeneratedPassword_Response>(MirandaImposeNextGeneratedPassword(password = password)).value
@Generated suspend fun mirandaImposeNextGeneratedUserToken(token:String): Unit = _askMiranda<MirandaImposeNextGeneratedUserToken_Response>(MirandaImposeNextGeneratedUserToken(token = token)).value
@Generated suspend fun mirandaImposeNextOrderID(id:Long): Unit = _askMiranda<MirandaImposeNextOrderID_Response>(MirandaImposeNextOrderID(id = id)).value
@Generated suspend fun mirandaGetGeneratedTestTimestamps(): List<String> = _askMiranda<MirandaGetGeneratedTestTimestamps_Response>(MirandaGetGeneratedTestTimestamps()).value
