/*
 * APS
 *
 * (C) Copyright 2015-2017 Vladimir Grechka
 *
 * YOU DON'T MESS AROUND WITH THIS SHIT, IT WAS GENERATED BY A TOOL SMARTER THAN YOU
 */

package aps.back

import aps.*
import kotlin.reflect.KClass


// ==================================================================
// REMOTE PROCEDURE SKELETONS
// ==================================================================

@Generated fun __MirandaImposeNextGeneratedPassword.serve(): __MirandaImposeNextGeneratedPassword_Response {
    return __MirandaImposeNextGeneratedPassword_Response(mirandaImposeNextGeneratedPassword(password = this.password))
}
@Generated fun __MirandaImposeNextGeneratedUserToken.serve(): __MirandaImposeNextGeneratedUserToken_Response {
    return __MirandaImposeNextGeneratedUserToken_Response(mirandaImposeNextGeneratedUserToken(token = this.token))
}
@Generated fun __MirandaImposeNextOrderID.serve(): __MirandaImposeNextOrderID_Response {
    return __MirandaImposeNextOrderID_Response(mirandaImposeNextOrderID(id = this.id))
}
@Generated fun __MirandaGetGeneratedTestTimestamps.serve(): __MirandaGetGeneratedTestTimestamps_Response {
    return __MirandaGetGeneratedTestTimestamps_Response(mirandaGetGeneratedTestTimestamps())
}
@Generated fun __MirandaSeedSomeStuff1.serve(): __MirandaSeedSomeStuff1_Response {
    return __MirandaSeedSomeStuff1_Response(mirandaSeedSomeStuff1())
}
@Generated fun __MirandaSaveRequestResponseLog.serve(): __MirandaSaveRequestResponseLog_Response {
    return __MirandaSaveRequestResponseLog_Response(mirandaSaveRequestResponseLog(name = this.name))
}
@Generated fun __MirandaMapStack.serve(): __MirandaMapStack_Response {
    return __MirandaMapStack_Response(mirandaMapStack(rawStack = this.rawStack))
}
@Generated fun __MirandaGetSentEmails.serve(): __MirandaGetSentEmails_Response {
    return __MirandaGetSentEmails_Response(mirandaGetSentEmails())
}
@Generated fun __MirandaClearSentEmails.serve(): __MirandaClearSentEmails_Response {
    return __MirandaClearSentEmails_Response(mirandaClearSentEmails())
}
@Generated fun __MirandaImposeNextRequestTimestamp.serve(): __MirandaImposeNextRequestTimestamp_Response {
    return __MirandaImposeNextRequestTimestamp_Response(mirandaImposeNextRequestTimestamp(stamp = this.stamp))
}
@Generated fun __MirandaImposeNextRequestError.serve(): __MirandaImposeNextRequestError_Response {
    return __MirandaImposeNextRequestError_Response(mirandaImposeNextRequestError(error = this.error))
}
@Generated fun __MirandaImposeNextGeneratedConfirmationSecret.serve(): __MirandaImposeNextGeneratedConfirmationSecret_Response {
    return __MirandaImposeNextGeneratedConfirmationSecret_Response(mirandaImposeNextGeneratedConfirmationSecret(secret = this.secret))
}
@Generated fun __MirandaPing.serve(): __MirandaPing_Response {
    return __MirandaPing_Response(mirandaPing())
}
@Generated fun __MirandaGetSoftwareVersion.serve(): __MirandaGetSoftwareVersion_Response {
    return __MirandaGetSoftwareVersion_Response(mirandaGetSoftwareVersion())
}
@Generated fun __ReginaLoadUser.serve(): __ReginaLoadUser_Response {
    return __ReginaLoadUser_Response(reginaLoadUser(userID = this.userID))
}
@Generated fun __ReginaAcceptProfile.serve(): __ReginaAcceptProfile_Response {
    return __ReginaAcceptProfile_Response(reginaAcceptProfile(userID = this.userID))
}
@Generated fun __ReginaCustomerSendOrderForApprovalAfterFixing.serve(): __ReginaCustomerSendOrderForApprovalAfterFixing_Response {
    return __ReginaCustomerSendOrderForApprovalAfterFixing_Response(reginaCustomerSendOrderForApprovalAfterFixing(orderID = this.orderID))
}
@Generated fun __ReginaAdminSendOrderToStore.serve(): __ReginaAdminSendOrderToStore_Response {
    return __ReginaAdminSendOrderToStore_Response(reginaAdminSendOrderToStore(orderID = this.orderID))
}
@Generated fun __ReginaLoadUAOrder.serve(): __ReginaLoadUAOrder_Response {
    return __ReginaLoadUAOrder_Response(reginaLoadUAOrder(id = this.id))
}
@Generated fun __ReginaGetDocumentCategories.serve(): __ReginaGetDocumentCategories_Response {
    return __ReginaGetDocumentCategories_Response(reginaGetDocumentCategories())
}
@Generated fun __ReginaGetMyself.serve(): __ReginaGetMyself_Response {
    return __ReginaGetMyself_Response(reginaGetMyself())
}
@Generated fun <T : HistoryItemRTOFields> __ReginaGetPairOfLastHistoryItems<T>.serve(): __ReginaGetPairOfLastHistoryItems_Response<T> {
    return __ReginaGetPairOfLastHistoryItems_Response(reginaGetPairOfLastHistoryItems(type = this.type, entityID = this.entityID))
}
