/*
 * APS
 *
 * (C) Copyright 2015-2017 Vladimir Grechka
 *
 * YOU DON'T MESS AROUND WITH THIS SHIT, IT WAS GENERATED BY A TOOL SMARTER THAN YOU
 */

package aps.back

import aps.*

@Generated fun MirandaImposeNextGeneratedPassword.serve() {
    mirandaImposeNextGeneratedPassword(password = this.password)
}
@Generated fun MirandaImposeNextGeneratedUserToken.serve() {
    mirandaImposeNextGeneratedUserToken(token = this.token)
}
@Generated fun MirandaImposeNextOrderID.serve() {
    mirandaImposeNextOrderID(id = this.id)
}
