/*
 * APS
 *
 * (C) Copyright 2015-2017 Vladimir Grechka
 *
 * YOU DON'T MESS AROUND WITH THIS SHIT, IT WAS GENERATED BY A TOOL SMARTER THAN YOU
 */

package aps.back

import aps.*

@Generated fun MirandaImposeNextGeneratedPassword.serve(): MirandaImposeNextGeneratedPassword_Response {
    return MirandaImposeNextGeneratedPassword_Response(mirandaImposeNextGeneratedPassword(password = this.password))
}
@Generated fun MirandaImposeNextGeneratedUserToken.serve(): MirandaImposeNextGeneratedUserToken_Response {
    return MirandaImposeNextGeneratedUserToken_Response(mirandaImposeNextGeneratedUserToken(token = this.token))
}
@Generated fun MirandaImposeNextOrderID.serve(): MirandaImposeNextOrderID_Response {
    return MirandaImposeNextOrderID_Response(mirandaImposeNextOrderID(id = this.id))
}
@Generated fun MirandaGetGeneratedTestTimestamps.serve(): MirandaGetGeneratedTestTimestamps_Response {
    return MirandaGetGeneratedTestTimestamps_Response(mirandaGetGeneratedTestTimestamps())
}
@Generated fun MirandaSeedSomeStuff1.serve(): MirandaSeedSomeStuff1_Response {
    return MirandaSeedSomeStuff1_Response(mirandaSeedSomeStuff1())
}
