module.exports = {
    'qweqweqwe': {
        
    }, // end of generated piece of shit
    
    '10b64318-d180-4a84-9b2f-0a37e61b3d4b': {
        
         'TopNavItem-blog': { title: `Блог` },
          'TopNavItem-contact': { title: `Связь` },
          'TopNavItem-dashboard': { title: `Люк` },
          'TopNavItem-faq': { title: `ЧаВо` },
          'TopNavItem-orders': { title: `Мои заказы` },
          'TopNavItem-prices': { title: `Цены` },
          'TopNavItem-samples': { title: `Примеры` },
          'TopNavItem-support': { active: true, title: `Поддержка` },
          'TopNavItem-why': { title: `Почему мы?` },
          'chunk-i000.thread-i000.link-topic': { title: `И это называется следственной документацией!` },
          'chunk-i000.thread-i000.newMessages.message-i000.message': `Take it easy, Luke. We hear your pain and are working hard to find a solution to your problem.\n\n(In other words, fuck you :))`,
          'chunk-i000.thread-i000.newMessages.message-i000.newLabel': `Новое`,
          'chunk-i000.thread-i000.newMessages.message-i000.timestamp': `27/07/2016 18:52:46`,
          'chunk-i000.thread-i000.newMessages.message-i000.userLabel-from': `Тодд Суппортод`,
          'chunk-i000.thread-i000.newMessages.message-i000.userLabel-to': `Люк Хуюк`,
          'chunk-i000.thread-i000.oldMessages.message-i000.message': `Нужно было бы еще многое вам сказать. Пришлось изложить только вкратце. Но я надеюсь, что вы меня поняли.`,
          'chunk-i000.thread-i000.oldMessages.message-i000.timestamp': `10/04/2014 16:44:55`,
          'chunk-i000.thread-i000.oldMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i000.oldMessages.message-i000.userLabel-from': `Люк Хуюк`,
          'liveBadge-topNavItem-support': `1`,
          pageHeader: `Поддержка`,
          'tab-main-i000:active.link-it': { title: `Обновленные` },
          'tab-main-i001.link-it': { title: `Все` },
          url: `http://aps-ua-writer.local:3022/support.html`
    }, // end of generated piece of shit

    '0f95a4f1-b8c5-4e33-b1dd-81204d94f2d8': {
        
         'TopNavItem-blog': { title: `Блог` },
          'TopNavItem-contact': { title: `Связь` },
          'TopNavItem-dashboard': { active: true, title: `Люк` },
          'TopNavItem-faq': { title: `ЧаВо` },
          'TopNavItem-orders': { title: `Мои заказы` },
          'TopNavItem-prices': { title: `Цены` },
          'TopNavItem-samples': { title: `Примеры` },
          'TopNavItem-support': { title: `Поддержка` },
          'TopNavItem-why': { title: `Почему мы?` },
          'link-changePassword': { title: `Сменить пароль` },
          'link-signOut': { title: `Выйти прочь` },
          'liveBadge-topNavItem-support': `1`,
          pageHeader: `Панель`,
          url: `http://aps-ua-writer.local:3022/dashboard.html`
    }, // end of generated piece of shit

    'c0950b79-938e-4bc0-b133-42d8a27d005f': {
        
         'Select-ordering': 
           { title: `Сначала новые`,
             titles: [ `Сначала новые`, `Сначала старые` ] },
          'TopNavItem-blog': { title: `Блог` },
          'TopNavItem-contact': { title: `Связь` },
          'TopNavItem-dashboard': { title: `Люк` },
          'TopNavItem-faq': { title: `ЧаВо` },
          'TopNavItem-orders': { title: `Мои заказы` },
          'TopNavItem-prices': { title: `Цены` },
          'TopNavItem-samples': { title: `Примеры` },
          'TopNavItem-support': { active: true, title: `Поддержка` },
          'TopNavItem-why': { title: `Почему мы?` },
          'button-edit': { icon: `edit` },
          'button-plus': { icon: `comment` },
          'chunk-i000.message-i000.message': `Take it easy, Luke. We hear your pain and are working hard to find a solution to your problem.\n\n(In other words, fuck you :))`,
          'chunk-i000.message-i000.newLabel': `Новое`,
          'chunk-i000.message-i000.timestamp': `27/07/2016 18:52:46`,
          'chunk-i000.message-i000.userLabel-from': `Тодд Суппортод`,
          'chunk-i000.message-i000.userLabel-to': `Люк Хуюк`,
          'chunk-i000.message-i001.message': `Нужно было бы еще многое вам сказать. Пришлось изложить только вкратце. Но я надеюсь, что вы меня поняли.`,
          'chunk-i000.message-i001.timestamp': `10/04/2014 16:44:55`,
          'chunk-i000.message-i001.to': `В рельсу`,
          'chunk-i000.message-i001.userLabel-from': `Люк Хуюк`,
          'liveBadge-topNavItem-support': `1`,
          pageHeader: `Запрос в поддержку № 12`,
          url: `http://aps-ua-writer.local:3022/support.html?thread=12`
    }, // end of generated piece of shit

    '866bef17-2783-40a5-860d-0d2f69966664': {
        'link-changePassword.title': `Сменить пароль`,
          'link-signOut.title': `Выйти прочь`,
          'pageHeader.title': `Панель`,
          'topNavLeft.TopNavItem-i000.badge': `13`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.active': true,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/dashboard.html`
    }, // end of generated piece of shit

    '1c3a4a15-4bc4-46f6-afd9-d23433c6d839': {
        'button-showMore.title': `Показать еще`,
          'chunk-i000.thread-i000.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i000.button-takeAndReply.shame': `button-takeAndReply-12`,
          'chunk-i000.thread-i000.newMessages.message-i000.message': `Нужно было бы еще многое вам сказать. Пришлось изложить только вкратце. Но я надеюсь, что вы меня поняли.`,
          'chunk-i000.thread-i000.newMessages.message-i000.timestamp': `10/04/2014 16:44:55`,
          'chunk-i000.thread-i000.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i000.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i000.newMessages.message-i000.userLabel-from.title': `Люк Хуюк`,
          'chunk-i000.thread-i000.topic': `№12 И это называется следственной документацией!`,
          'chunk-i000.thread-i001.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i001.button-takeAndReply.shame': `button-takeAndReply-25`,
          'chunk-i000.thread-i001.newMessages.message-i000.message': `В  окно  напротив уже высунулись те же старики, но зрителей там\nприбавилось:  за  их  спинами  возвышался  огромный  мужчина  в\nраскрытой  на  груди  рубахе, который все время крутил и вертел\nсвою рыжеватую бородку.\n     - Йозеф К.? - спросил инспектор, должно быть,  только  для\nтого, чтобы обратить на себя рассеянный взгляд К.\n     К. наклонил голову.\n     - Должно  быть,  вас  очень  удивили  события сегодняшнего\nутра?`,
          'chunk-i000.thread-i001.newMessages.message-i000.timestamp': `06/05/2014 17:33:34`,
          'chunk-i000.thread-i001.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i001.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i001.newMessages.message-i000.userLabel-from.title': `Даздраперма Дивизионная`,
          'chunk-i000.thread-i001.topic': `№25 В   углу   комнаты   стояли  трое  молодых  людей  -  они разглядывали фотографии фройляйн Бюрстнер,\nвоткнутые в плетеную циновку на стене. На ручке открытого окна висела белая  блузка.`,
          'chunk-i000.thread-i002.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i002.button-takeAndReply.shame': `button-takeAndReply-308`,
          'chunk-i000.thread-i002.newMessages.message-i000.message': `Всю следующую неделю К.  изо  дня  в  день  ожидал  нового вызова,  он  не  мог  поверить,  что его отказ от допроса будет принят буквально, а когда ожидаемый вызов до субботы так  и  не пришел, К. усмотрел в этом молчании приглашение в тот же дом на тот  же  час.  Поэтому в воскресенье он снова отправился туда и прямо прошел по этажам и коридорам  наверх;  некоторые  жильцы, запомнившие его, здоровались с ним у дверей, но ему не пришлось никого  спрашивать,  и  он  сам подошел к нужной двери. На стук открыли сразу, и,  не  оглядываясь  на  уже  знакомую  женщину, остановившуюся у дверей, он хотел пройти в следующую комнату.`,
          'chunk-i000.thread-i002.newMessages.message-i000.timestamp': `17/05/2014 02:33:15`,
          'chunk-i000.thread-i002.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i002.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i002.newMessages.message-i000.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.thread-i002.newMessages.message-i001.continuation': `Вдогонку`,
          'chunk-i000.thread-i002.newMessages.message-i001.message': `Еще хотел бы добавить вот что.\n\n- Сегодня заседания нет, - сказала женщина.\n- Как это - нет заседания? - спросил он, не поверив.`,
          'chunk-i000.thread-i002.newMessages.message-i001.timestamp': `17/05/2014 02:35:27`,
          'chunk-i000.thread-i002.newMessages.message-i002.continuation': `Вдогонку`,
          'chunk-i000.thread-i002.newMessages.message-i002.message': `И еще немного... Чтобы  убедить  его,  женщина  отворила  дверь  в соседнее помещение.`,
          'chunk-i000.thread-i002.newMessages.message-i002.timestamp': `17/05/2014 02:36:02`,
          'chunk-i000.thread-i002.topic': `№308 В пустом зале заседаний. Студент. Канцелярии`,
          'chunk-i000.thread-i003.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i003.button-takeAndReply.shame': `button-takeAndReply-321`,
          'chunk-i000.thread-i003.newMessages.message-i000.message': `Я так и догадалась по вашей речи. Мне лично она  очень  понравилась.  Правда,  я  не  все  слышала - начало пропустила, а под конец лежала со студентом на полу.`,
          'chunk-i000.thread-i003.newMessages.message-i000.timestamp': `21/05/2014 10:11:59`,
          'chunk-i000.thread-i003.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i003.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i003.newMessages.message-i000.userLabel-from.title': `Джейн Остин`,
          'chunk-i000.thread-i003.topic': `№321 Видно,  собираетесь  навести  здесь  порядок?`,
          'chunk-i000.thread-i004.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i004.button-takeAndReply.shame': `button-takeAndReply-405`,
          'chunk-i000.thread-i004.newMessages.message-i000.message': `Книги были старые, потрепанные, на одной  переплет был переломлен и обе половинки держались на ниточке.`,
          'chunk-i000.thread-i004.newMessages.message-i000.timestamp': `26/05/2014 10:51:24`,
          'chunk-i000.thread-i004.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i004.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i004.newMessages.message-i000.userLabel-from.title': `Жорж Санд`,
          'chunk-i000.thread-i004.topic': `№405 Ну  конечно  же!`,
          'chunk-i000.thread-i005.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i005.button-takeAndReply.shame': `button-takeAndReply-708`,
          'chunk-i000.thread-i005.newMessages.message-i000.message': `И женщине пришлось смахнуть пыль фартуком хотя бы сверху,  прежде чем К. мог взяться за книгу.`,
          'chunk-i000.thread-i005.newMessages.message-i000.timestamp': `13/06/2014 14:19:32`,
          'chunk-i000.thread-i005.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i005.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i005.newMessages.message-i000.userLabel-from.title': `Василий Теркин`,
          'chunk-i000.thread-i005.newMessages.message-i001.continuation': `Вдогонку`,
          'chunk-i000.thread-i005.newMessages.message-i001.message': `Он  открыл  ту,  что  лежала  сверху, и увидел неприличную картинку.`,
          'chunk-i000.thread-i005.newMessages.message-i001.timestamp': `13/06/2014 14:25:13`,
          'chunk-i000.thread-i005.topic': `№708 Какая  тут  везде грязь, - сказал К., покачав головой`,
          'chunk-i000.thread-i006.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i006.button-takeAndReply.shame': `button-takeAndReply-914`,
          'chunk-i000.thread-i006.newMessages.message-i000.message': `- Я вам помогу! - сказала женщина. - Согласны?\n- Но разве вы и вправду можете мне  помочь,  не  подвергая себя  опасности?  Ведь  вы  сами  сказали,  что ваш муж целиком зависит от своего начальства.\n- И все же я вам помогу, - сказала  женщина.  Подите  сюда, надо  все обсудить. А о том, что мне грозит опасность, говорить не стоит.  Я  только  тогда  пугаюсь  опасности,  когда  считаю нужным. Идите сюда.\n- Она показала на подмостки и попросила его сесть  рядом с ней на ступеньки.\n\n- У вас чудесные темные глаза, -сказала она, когда они сели, и заглянула К. в лицо. - Говорят, у меня тоже глаза красивые, но ваши куда красивее. Ведь  я  вас сразу  приметила,  еще  в первый раз, как только вы сюда зашли. Из-за вас я и пробралась потом в зал заседаний. Обычно я никогда этого не делаю, мне даже, собственно говоря,  запрещено  ходить сюда.`,
          'chunk-i000.thread-i006.newMessages.message-i000.timestamp': `16/07/2014 08:24:17`,
          'chunk-i000.thread-i006.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i006.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i006.newMessages.message-i000.userLabel-from.title': `Карлос Кастанеда`,
          'chunk-i000.thread-i006.topic': `№914 Так вот какие юридические книги тут изучают!`,
          'chunk-i000.thread-i007.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i007.button-takeAndReply.shame': `button-takeAndReply-933`,
          'chunk-i000.thread-i007.newMessages.message-i000.message': `Давно  могли уйти,  никто  и  не  заметил бы вашего отсутствия. Да, да, надо было вам уйти, как только я пришел, и уйти сразу, немедленно. В этих словах слышалась не только сдержанная злоба, в  них ясно  чувствовалось высокомерие будущего чиновника по отношению к неприятному для него обвиняемому.`,
          'chunk-i000.thread-i007.newMessages.message-i000.timestamp': `17/07/2014 10:33:08`,
          'chunk-i000.thread-i007.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i007.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i007.newMessages.message-i000.userLabel-from.title': `Тело Странное`,
          'chunk-i000.thread-i007.topic': `№933 Если вам так не терпится, можете  уходить`,
          'chunk-i000.thread-i008.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i008.button-takeAndReply.shame': `button-takeAndReply-951`,
          'chunk-i000.thread-i008.newMessages.message-i000.message': `Его за мной прислал следователь, мне с вами идти никак нельзя, этот маленький уродец, - тут  она провела  рукой  по лицу студента, этот маленький уродец меня не отпустит.`,
          'chunk-i000.thread-i008.newMessages.message-i000.timestamp': `06/08/2014 04:33:37`,
          'chunk-i000.thread-i008.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i008.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i008.newMessages.message-i000.userLabel-from.title': `Регина Дубовицкая`,
          'chunk-i000.thread-i008.topic': `№951 Ничего  не  поделаешь`,
          'chunk-i000.thread-i009.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i009.button-takeAndReply.shame': `button-takeAndReply-1011`,
          'chunk-i000.thread-i009.newMessages.message-i000.message': `К. все еще стоял в дверях. Он должен был признаться, что женщина не только обманула его, но и солгала, что ее несут к следователю. Не станет  же  следователь сидеть  на  чердаке  и  дожидаться  ее.`,
          'chunk-i000.thread-i009.newMessages.message-i000.timestamp': `15/08/2014 13:32:42`,
          'chunk-i000.thread-i009.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i009.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i009.newMessages.message-i000.userLabel-from.title': `Варсоновий Оптинский`,
          'chunk-i000.thread-i009.topic': `№1011 Оба  исчезли за поворотом`,
          'pageHeader.title': `Куча работы`,
          'tab-main-i000.active': true,
          'tab-main-i000.badge': `13`,
          'tab-main-i000.shame': `support`,
          'tab-main-i000.title': `Поддержка`,
          'topNavLeft.TopNavItem-i000.active': true,
          'topNavLeft.TopNavItem-i000.badge': `13`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/admin-heap.html`
    }, // end of generated piece of shit


    'edb9fdc5-841b-4232-baa2-dfdc39d8d02d': {
        'chunk-i000.thread-i000.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i000.button-takeAndReply.shame': `button-takeAndReply-12`,
          'chunk-i000.thread-i000.newMessages.message-i000.message': `Нужно было бы еще многое вам сказать. Пришлось изложить только вкратце. Но я надеюсь, что вы меня поняли.`,
          'chunk-i000.thread-i000.newMessages.message-i000.timestamp': `10/04/2014 16:44:55`,
          'chunk-i000.thread-i000.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i000.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i000.newMessages.message-i000.userLabel-from.title': `Люк Хуюк`,
          'chunk-i000.thread-i000.topic': `№12 И это называется следственной документацией!`,
          'chunk-i000.thread-i001.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i001.button-takeAndReply.shame': `button-takeAndReply-25`,
          'chunk-i000.thread-i001.newMessages.message-i000.message': `В  окно  напротив уже высунулись те же старики, но зрителей там\nприбавилось:  за  их  спинами  возвышался  огромный  мужчина  в\nраскрытой  на  груди  рубахе, который все время крутил и вертел\nсвою рыжеватую бородку.\n     - Йозеф К.? - спросил инспектор, должно быть,  только  для\nтого, чтобы обратить на себя рассеянный взгляд К.\n     К. наклонил голову.\n     - Должно  быть,  вас  очень  удивили  события сегодняшнего\nутра?`,
          'chunk-i000.thread-i001.newMessages.message-i000.timestamp': `06/05/2014 17:33:34`,
          'chunk-i000.thread-i001.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i001.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i001.newMessages.message-i000.userLabel-from.title': `Даздраперма Дивизионная`,
          'chunk-i000.thread-i001.topic': `№25 В   углу   комнаты   стояли  трое  молодых  людей  -  они разглядывали фотографии фройляйн Бюрстнер,\nвоткнутые в плетеную циновку на стене. На ручке открытого окна висела белая  блузка.`,
          'chunk-i000.thread-i002.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i002.button-takeAndReply.shame': `button-takeAndReply-308`,
          'chunk-i000.thread-i002.newMessages.message-i000.message': `Всю следующую неделю К.  изо  дня  в  день  ожидал  нового вызова,  он  не  мог  поверить,  что его отказ от допроса будет принят буквально, а когда ожидаемый вызов до субботы так  и  не пришел, К. усмотрел в этом молчании приглашение в тот же дом на тот  же  час.  Поэтому в воскресенье он снова отправился туда и прямо прошел по этажам и коридорам  наверх;  некоторые  жильцы, запомнившие его, здоровались с ним у дверей, но ему не пришлось никого  спрашивать,  и  он  сам подошел к нужной двери. На стук открыли сразу, и,  не  оглядываясь  на  уже  знакомую  женщину, остановившуюся у дверей, он хотел пройти в следующую комнату.`,
          'chunk-i000.thread-i002.newMessages.message-i000.timestamp': `17/05/2014 02:33:15`,
          'chunk-i000.thread-i002.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i002.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i002.newMessages.message-i000.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.thread-i002.newMessages.message-i001.continuation': `Вдогонку`,
          'chunk-i000.thread-i002.newMessages.message-i001.message': `Еще хотел бы добавить вот что.\n\n- Сегодня заседания нет, - сказала женщина.\n- Как это - нет заседания? - спросил он, не поверив.`,
          'chunk-i000.thread-i002.newMessages.message-i001.timestamp': `17/05/2014 02:35:27`,
          'chunk-i000.thread-i002.newMessages.message-i002.continuation': `Вдогонку`,
          'chunk-i000.thread-i002.newMessages.message-i002.message': `И еще немного... Чтобы  убедить  его,  женщина  отворила  дверь  в соседнее помещение.`,
          'chunk-i000.thread-i002.newMessages.message-i002.timestamp': `17/05/2014 02:36:02`,
          'chunk-i000.thread-i002.topic': `№308 В пустом зале заседаний. Студент. Канцелярии`,
          'chunk-i000.thread-i003.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i003.button-takeAndReply.shame': `button-takeAndReply-321`,
          'chunk-i000.thread-i003.newMessages.message-i000.message': `Я так и догадалась по вашей речи. Мне лично она  очень  понравилась.  Правда,  я  не  все  слышала - начало пропустила, а под конец лежала со студентом на полу.`,
          'chunk-i000.thread-i003.newMessages.message-i000.timestamp': `21/05/2014 10:11:59`,
          'chunk-i000.thread-i003.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i003.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i003.newMessages.message-i000.userLabel-from.title': `Джейн Остин`,
          'chunk-i000.thread-i003.topic': `№321 Видно,  собираетесь  навести  здесь  порядок?`,
          'chunk-i000.thread-i004.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i004.button-takeAndReply.shame': `button-takeAndReply-405`,
          'chunk-i000.thread-i004.newMessages.message-i000.message': `Книги были старые, потрепанные, на одной  переплет был переломлен и обе половинки держались на ниточке.`,
          'chunk-i000.thread-i004.newMessages.message-i000.timestamp': `26/05/2014 10:51:24`,
          'chunk-i000.thread-i004.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i004.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i004.newMessages.message-i000.userLabel-from.title': `Жорж Санд`,
          'chunk-i000.thread-i004.topic': `№405 Ну  конечно  же!`,
          'chunk-i000.thread-i005.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i005.button-takeAndReply.shame': `button-takeAndReply-708`,
          'chunk-i000.thread-i005.newMessages.message-i000.message': `И женщине пришлось смахнуть пыль фартуком хотя бы сверху,  прежде чем К. мог взяться за книгу.`,
          'chunk-i000.thread-i005.newMessages.message-i000.timestamp': `13/06/2014 14:19:32`,
          'chunk-i000.thread-i005.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i005.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i005.newMessages.message-i000.userLabel-from.title': `Василий Теркин`,
          'chunk-i000.thread-i005.newMessages.message-i001.continuation': `Вдогонку`,
          'chunk-i000.thread-i005.newMessages.message-i001.message': `Он  открыл  ту,  что  лежала  сверху, и увидел неприличную картинку.`,
          'chunk-i000.thread-i005.newMessages.message-i001.timestamp': `13/06/2014 14:25:13`,
          'chunk-i000.thread-i005.topic': `№708 Какая  тут  везде грязь, - сказал К., покачав головой`,
          'chunk-i000.thread-i006.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i006.button-takeAndReply.shame': `button-takeAndReply-914`,
          'chunk-i000.thread-i006.newMessages.message-i000.message': `- Я вам помогу! - сказала женщина. - Согласны?\n- Но разве вы и вправду можете мне  помочь,  не  подвергая себя  опасности?  Ведь  вы  сами  сказали,  что ваш муж целиком зависит от своего начальства.\n- И все же я вам помогу, - сказала  женщина.  Подите  сюда, надо  все обсудить. А о том, что мне грозит опасность, говорить не стоит.  Я  только  тогда  пугаюсь  опасности,  когда  считаю нужным. Идите сюда.\n- Она показала на подмостки и попросила его сесть  рядом с ней на ступеньки.\n\n- У вас чудесные темные глаза, -сказала она, когда они сели, и заглянула К. в лицо. - Говорят, у меня тоже глаза красивые, но ваши куда красивее. Ведь  я  вас сразу  приметила,  еще  в первый раз, как только вы сюда зашли. Из-за вас я и пробралась потом в зал заседаний. Обычно я никогда этого не делаю, мне даже, собственно говоря,  запрещено  ходить сюда.`,
          'chunk-i000.thread-i006.newMessages.message-i000.timestamp': `16/07/2014 08:24:17`,
          'chunk-i000.thread-i006.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i006.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i006.newMessages.message-i000.userLabel-from.title': `Карлос Кастанеда`,
          'chunk-i000.thread-i006.topic': `№914 Так вот какие юридические книги тут изучают!`,
          'chunk-i000.thread-i007.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i007.button-takeAndReply.shame': `button-takeAndReply-933`,
          'chunk-i000.thread-i007.newMessages.message-i000.message': `Давно  могли уйти,  никто  и  не  заметил бы вашего отсутствия. Да, да, надо было вам уйти, как только я пришел, и уйти сразу, немедленно. В этих словах слышалась не только сдержанная злоба, в  них ясно  чувствовалось высокомерие будущего чиновника по отношению к неприятному для него обвиняемому.`,
          'chunk-i000.thread-i007.newMessages.message-i000.timestamp': `17/07/2014 10:33:08`,
          'chunk-i000.thread-i007.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i007.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i007.newMessages.message-i000.userLabel-from.title': `Тело Странное`,
          'chunk-i000.thread-i007.topic': `№933 Если вам так не терпится, можете  уходить`,
          'chunk-i000.thread-i008.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i008.button-takeAndReply.shame': `button-takeAndReply-951`,
          'chunk-i000.thread-i008.newMessages.message-i000.message': `Его за мной прислал следователь, мне с вами идти никак нельзя, этот маленький уродец, - тут  она провела  рукой  по лицу студента, этот маленький уродец меня не отпустит.`,
          'chunk-i000.thread-i008.newMessages.message-i000.timestamp': `06/08/2014 04:33:37`,
          'chunk-i000.thread-i008.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i008.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i008.newMessages.message-i000.userLabel-from.title': `Регина Дубовицкая`,
          'chunk-i000.thread-i008.topic': `№951 Ничего  не  поделаешь`,
          'chunk-i000.thread-i009.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i009.button-takeAndReply.shame': `button-takeAndReply-1011`,
          'chunk-i000.thread-i009.newMessages.message-i000.message': `К. все еще стоял в дверях. Он должен был признаться, что женщина не только обманула его, но и солгала, что ее несут к следователю. Не станет  же  следователь сидеть  на  чердаке  и  дожидаться  ее.`,
          'chunk-i000.thread-i009.newMessages.message-i000.timestamp': `15/08/2014 13:32:42`,
          'chunk-i000.thread-i009.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i009.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i009.newMessages.message-i000.userLabel-from.title': `Варсоновий Оптинский`,
          'chunk-i000.thread-i009.topic': `№1011 Оба  исчезли за поворотом`,
          'chunk-i001.thread-i000.button-takeAndReply.icon': `comment`,
          'chunk-i001.thread-i000.button-takeAndReply.shame': `button-takeAndReply-1134`,
          'chunk-i001.thread-i000.newMessages.message-i000.message': `Вечно  ее  от  меня уносят.  Сегодня воскресенье, работать я не обязан, а мне вдруг дают совершенно ненужные  поручения,  лишь  бы  услать  отсюда.`,
          'chunk-i001.thread-i000.newMessages.message-i000.timestamp': `11/10/2014 08:15:11`,
          'chunk-i001.thread-i000.newMessages.message-i000.to': `В рельсу`,
          'chunk-i001.thread-i000.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i001.thread-i000.newMessages.message-i000.userLabel-from.title': `Федор Достоевский`,
          'chunk-i001.thread-i000.topic': `№1134 Вот видите!`,
          'chunk-i001.thread-i001.button-takeAndReply.icon': `comment`,
          'chunk-i001.thread-i001.button-takeAndReply.shame': `button-takeAndReply-1225`,
          'chunk-i001.thread-i001.newMessages.message-i000.message': `- Другого не вижу, - сказал  служитель.  -  И  главное,  с\nкаждым  днем все хуже: до сих пор он таскал ее только к себе, а\nсейчас  потащил  к  самому  следователю;   впрочем,   этого   я\nдавным-давно ждал.`,
          'chunk-i001.thread-i001.newMessages.message-i000.timestamp': `23/10/2014 18:10:13`,
          'chunk-i001.thread-i001.newMessages.message-i000.to': `В рельсу`,
          'chunk-i001.thread-i001.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i001.thread-i001.newMessages.message-i000.userLabel-from.title': `Ксенофонт Тутанский`,
          'chunk-i001.thread-i001.topic': `№1225 А разве другого выхода нет?`,
          'chunk-i001.thread-i002.button-takeAndReply.icon': `comment`,
          'chunk-i001.thread-i002.button-takeAndReply.shame': `button-takeAndReply-1372`,
          'chunk-i001.thread-i002.newMessages.message-i000.message': `Да  кто  вы  такой?  Ищете  смысл,  а  творите  такую\nбессмыслицу, что и не придумаешь. Да тут камни возопят! Сначала\nэти господа на меня напали, а теперь расселись, стоят и глазеют\nвсем скопом, как я пляшу под вашу  дудку.  И  еще  спрашиваете,\nкакой  смысл  звонить  прокурору,  когда  мне  сказано,  что  я\nарестован! Хорошо, я не буду звонить!`,
          'chunk-i001.thread-i002.newMessages.message-i000.timestamp': `25/11/2014 05:39:53`,
          'chunk-i001.thread-i002.newMessages.message-i000.to': `В рельсу`,
          'chunk-i001.thread-i002.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i001.thread-i002.newMessages.message-i000.userLabel-from.title': `Евгений Ваганович`,
          'chunk-i001.thread-i002.topic': `№1372 Какой смысл?`,
          'pageHeader.title': `Куча работы`,
          'tab-main-i000.active': true,
          'tab-main-i000.badge': `13`,
          'tab-main-i000.shame': `support`,
          'tab-main-i000.title': `Поддержка`,
          'topNavLeft.TopNavItem-i000.active': true,
          'topNavLeft.TopNavItem-i000.badge': `13`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/admin-heap.html`
    }, // end of generated piece of shit

    '404c23b9-e496-41b5-a105-71ae5c44ed5f': {
        'Select-ordering.item-i000.title': `Сначала новые`,
          'Select-ordering.item-i000.value': `desc`,
          'Select-ordering.item-i001.title': `Сначала старые`,
          'Select-ordering.item-i001.value': `asc`,
          'Select-ordering.selected.title': `Сначала новые`,
          'Select-ordering.selected.value': `desc`,
          'button-edit.icon': `edit`,
          'button-plus.icon': `comment`,
          'chunk-i000.message-i000.message': `И еще немного... Чтобы  убедить  его,  женщина  отворила  дверь  в соседнее помещение.`,
          'chunk-i000.message-i000.newLabel': `Новое`,
          'chunk-i000.message-i000.timestamp': `17/05/2014 02:36:02`,
          'chunk-i000.message-i000.to': `В рельсу`,
          'chunk-i000.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i000.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i001.message': `Еще хотел бы добавить вот что.\n\n- Сегодня заседания нет, - сказала женщина.\n- Как это - нет заседания? - спросил он, не поверив.`,
          'chunk-i000.message-i001.newLabel': `Новое`,
          'chunk-i000.message-i001.timestamp': `17/05/2014 02:35:27`,
          'chunk-i000.message-i001.to': `В рельсу`,
          'chunk-i000.message-i001.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i001.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i002.message': `Всю следующую неделю К.  изо  дня  в  день  ожидал  нового вызова,  он  не  мог  поверить,  что его отказ от допроса будет принят буквально, а когда ожидаемый вызов до субботы так  и  не пришел, К. усмотрел в этом молчании приглашение в тот же дом на тот  же  час.  Поэтому в воскресенье он снова отправился туда и прямо прошел по этажам и коридорам  наверх;  некоторые  жильцы, запомнившие его, здоровались с ним у дверей, но ему не пришлось никого  спрашивать,  и  он  сам подошел к нужной двери. На стук открыли сразу, и,  не  оглядываясь  на  уже  знакомую  женщину, остановившуюся у дверей, он хотел пройти в следующую комнату.`,
          'chunk-i000.message-i002.newLabel': `Новое`,
          'chunk-i000.message-i002.timestamp': `17/05/2014 02:33:15`,
          'chunk-i000.message-i002.to': `В рельсу`,
          'chunk-i000.message-i002.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i002.userLabel-from.title': `Франц Кафка`,
          'pageHeader.title': `Запрос в поддержку № 308`,
          pageTopBlockQuote: `В пустом зале заседаний. Студент. Канцелярии`,
          'topNavLeft.TopNavItem-i000.badge': `12`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.active': true,
          'topNavLeft.TopNavItem-i001.badge': `3/1`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/support.html?thread=308`
    }, // end of generated piece of shit

    '8fc8247d-2b0a-492b-a495-ee782f56eeb4': {
        'button-showMore.title': `Показать еще`,
          'chunk-i000.thread-i000.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i000.button-takeAndReply.shame': `button-takeAndReply-12`,
          'chunk-i000.thread-i000.newMessages.message-i000.message': `Нужно было бы еще многое вам сказать. Пришлось изложить только вкратце. Но я надеюсь, что вы меня поняли.`,
          'chunk-i000.thread-i000.newMessages.message-i000.timestamp': `10/04/2014 16:44:55`,
          'chunk-i000.thread-i000.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i000.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i000.newMessages.message-i000.userLabel-from.title': `Люк Хуюк`,
          'chunk-i000.thread-i000.topic': `№12 И это называется следственной документацией!`,
          'chunk-i000.thread-i001.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i001.button-takeAndReply.shame': `button-takeAndReply-25`,
          'chunk-i000.thread-i001.newMessages.message-i000.message': `В  окно  напротив уже высунулись те же старики, но зрителей там\nприбавилось:  за  их  спинами  возвышался  огромный  мужчина  в\nраскрытой  на  груди  рубахе, который все время крутил и вертел\nсвою рыжеватую бородку.\n     - Йозеф К.? - спросил инспектор, должно быть,  только  для\nтого, чтобы обратить на себя рассеянный взгляд К.\n     К. наклонил голову.\n     - Должно  быть,  вас  очень  удивили  события сегодняшнего\nутра?`,
          'chunk-i000.thread-i001.newMessages.message-i000.timestamp': `06/05/2014 17:33:34`,
          'chunk-i000.thread-i001.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i001.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i001.newMessages.message-i000.userLabel-from.title': `Даздраперма Дивизионная`,
          'chunk-i000.thread-i001.topic': `№25 В   углу   комнаты   стояли  трое  молодых  людей  -  они разглядывали фотографии фройляйн Бюрстнер,\nвоткнутые в плетеную циновку на стене. На ручке открытого окна висела белая  блузка.`,
          'chunk-i000.thread-i002.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i002.button-takeAndReply.shame': `button-takeAndReply-321`,
          'chunk-i000.thread-i002.newMessages.message-i000.message': `Я так и догадалась по вашей речи. Мне лично она  очень  понравилась.  Правда,  я  не  все  слышала - начало пропустила, а под конец лежала со студентом на полу.`,
          'chunk-i000.thread-i002.newMessages.message-i000.timestamp': `21/05/2014 10:11:59`,
          'chunk-i000.thread-i002.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i002.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i002.newMessages.message-i000.userLabel-from.title': `Джейн Остин`,
          'chunk-i000.thread-i002.topic': `№321 Видно,  собираетесь  навести  здесь  порядок?`,
          'chunk-i000.thread-i003.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i003.button-takeAndReply.shame': `button-takeAndReply-405`,
          'chunk-i000.thread-i003.newMessages.message-i000.message': `Книги были старые, потрепанные, на одной  переплет был переломлен и обе половинки держались на ниточке.`,
          'chunk-i000.thread-i003.newMessages.message-i000.timestamp': `26/05/2014 10:51:24`,
          'chunk-i000.thread-i003.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i003.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i003.newMessages.message-i000.userLabel-from.title': `Жорж Санд`,
          'chunk-i000.thread-i003.topic': `№405 Ну  конечно  же!`,
          'chunk-i000.thread-i004.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i004.button-takeAndReply.shame': `button-takeAndReply-708`,
          'chunk-i000.thread-i004.newMessages.message-i000.message': `И женщине пришлось смахнуть пыль фартуком хотя бы сверху,  прежде чем К. мог взяться за книгу.`,
          'chunk-i000.thread-i004.newMessages.message-i000.timestamp': `13/06/2014 14:19:32`,
          'chunk-i000.thread-i004.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i004.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i004.newMessages.message-i000.userLabel-from.title': `Василий Теркин`,
          'chunk-i000.thread-i004.newMessages.message-i001.continuation': `Вдогонку`,
          'chunk-i000.thread-i004.newMessages.message-i001.message': `Он  открыл  ту,  что  лежала  сверху, и увидел неприличную картинку.`,
          'chunk-i000.thread-i004.newMessages.message-i001.timestamp': `13/06/2014 14:25:13`,
          'chunk-i000.thread-i004.topic': `№708 Какая  тут  везде грязь, - сказал К., покачав головой`,
          'chunk-i000.thread-i005.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i005.button-takeAndReply.shame': `button-takeAndReply-914`,
          'chunk-i000.thread-i005.newMessages.message-i000.message': `- Я вам помогу! - сказала женщина. - Согласны?\n- Но разве вы и вправду можете мне  помочь,  не  подвергая себя  опасности?  Ведь  вы  сами  сказали,  что ваш муж целиком зависит от своего начальства.\n- И все же я вам помогу, - сказала  женщина.  Подите  сюда, надо  все обсудить. А о том, что мне грозит опасность, говорить не стоит.  Я  только  тогда  пугаюсь  опасности,  когда  считаю нужным. Идите сюда.\n- Она показала на подмостки и попросила его сесть  рядом с ней на ступеньки.\n\n- У вас чудесные темные глаза, -сказала она, когда они сели, и заглянула К. в лицо. - Говорят, у меня тоже глаза красивые, но ваши куда красивее. Ведь  я  вас сразу  приметила,  еще  в первый раз, как только вы сюда зашли. Из-за вас я и пробралась потом в зал заседаний. Обычно я никогда этого не делаю, мне даже, собственно говоря,  запрещено  ходить сюда.`,
          'chunk-i000.thread-i005.newMessages.message-i000.timestamp': `16/07/2014 08:24:17`,
          'chunk-i000.thread-i005.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i005.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i005.newMessages.message-i000.userLabel-from.title': `Карлос Кастанеда`,
          'chunk-i000.thread-i005.topic': `№914 Так вот какие юридические книги тут изучают!`,
          'chunk-i000.thread-i006.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i006.button-takeAndReply.shame': `button-takeAndReply-933`,
          'chunk-i000.thread-i006.newMessages.message-i000.message': `Давно  могли уйти,  никто  и  не  заметил бы вашего отсутствия. Да, да, надо было вам уйти, как только я пришел, и уйти сразу, немедленно. В этих словах слышалась не только сдержанная злоба, в  них ясно  чувствовалось высокомерие будущего чиновника по отношению к неприятному для него обвиняемому.`,
          'chunk-i000.thread-i006.newMessages.message-i000.timestamp': `17/07/2014 10:33:08`,
          'chunk-i000.thread-i006.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i006.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i006.newMessages.message-i000.userLabel-from.title': `Тело Странное`,
          'chunk-i000.thread-i006.topic': `№933 Если вам так не терпится, можете  уходить`,
          'chunk-i000.thread-i007.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i007.button-takeAndReply.shame': `button-takeAndReply-951`,
          'chunk-i000.thread-i007.newMessages.message-i000.message': `Его за мной прислал следователь, мне с вами идти никак нельзя, этот маленький уродец, - тут  она провела  рукой  по лицу студента, этот маленький уродец меня не отпустит.`,
          'chunk-i000.thread-i007.newMessages.message-i000.timestamp': `06/08/2014 04:33:37`,
          'chunk-i000.thread-i007.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i007.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i007.newMessages.message-i000.userLabel-from.title': `Регина Дубовицкая`,
          'chunk-i000.thread-i007.topic': `№951 Ничего  не  поделаешь`,
          'chunk-i000.thread-i008.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i008.button-takeAndReply.shame': `button-takeAndReply-1011`,
          'chunk-i000.thread-i008.newMessages.message-i000.message': `К. все еще стоял в дверях. Он должен был признаться, что женщина не только обманула его, но и солгала, что ее несут к следователю. Не станет  же  следователь сидеть  на  чердаке  и  дожидаться  ее.`,
          'chunk-i000.thread-i008.newMessages.message-i000.timestamp': `15/08/2014 13:32:42`,
          'chunk-i000.thread-i008.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i008.newMessages.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i008.newMessages.message-i000.userLabel-from.title': `Варсоновий Оптинский`,
          'chunk-i000.thread-i008.topic': `№1011 Оба  исчезли за поворотом`,
          'chunk-i000.thread-i009.button-takeAndReply.icon': `comment`,
          'chunk-i000.thread-i009.button-takeAndReply.shame': `button-takeAndReply-1134`,
          'chunk-i000.thread-i009.newMessages.message-i000.message': `Вечно  ее  от  меня уносят.  Сегодня воскресенье, работать я не обязан, а мне вдруг дают совершенно ненужные  поручения,  лишь  бы  услать  отсюда.`,
          'chunk-i000.thread-i009.newMessages.message-i000.timestamp': `11/10/2014 08:15:11`,
          'chunk-i000.thread-i009.newMessages.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i009.newMessages.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i009.newMessages.message-i000.userLabel-from.title': `Федор Достоевский`,
          'chunk-i000.thread-i009.topic': `№1134 Вот видите!`,
          'pageHeader.title': `Куча работы`,
          'tab-main-i000.active': true,
          'tab-main-i000.badge': `12`,
          'tab-main-i000.shame': `support`,
          'tab-main-i000.title': `Поддержка`,
          'topNavLeft.TopNavItem-i000.active': true,
          'topNavLeft.TopNavItem-i000.badge': `12`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.badge': `3/1`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/admin-heap.html`
    }, // end of generated piece of shit

    '9dde55d6-0488-4ec6-9443-a96370c7fd4b': {
        'Select-ordering.item-i000.title': `Сначала новые`,
          'Select-ordering.item-i000.value': `desc`,
          'Select-ordering.item-i001.title': `Сначала старые`,
          'Select-ordering.item-i001.value': `asc`,
          'Select-ordering.selected.title': `Сначала новые`,
          'Select-ordering.selected.value': `desc`,
          'button-edit.icon': `edit`,
          'button-plus.icon': `comment`,
          'chunk-i000.message-i000.message': `Нужно было бы еще многое вам сказать. Пришлось изложить только вкратце. Но я надеюсь, что вы меня поняли.`,
          'chunk-i000.message-i000.newLabel': `Новое`,
          'chunk-i000.message-i000.timestamp': `10/04/2014 16:44:55`,
          'chunk-i000.message-i000.to': `В рельсу`,
          'chunk-i000.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.message-i000.userLabel-from.title': `Люк Хуюк`,
          'pageHeader.title': `Запрос в поддержку № 12`,
          pageTopBlockQuote: `И это называется следственной документацией!`,
          'topNavLeft.TopNavItem-i000.badge': `11`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.active': true,
          'topNavLeft.TopNavItem-i001.badge': `4/2`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/support.html?thread=12`
    }, // end of generated piece of shit

    '0020d0bf-5a2c-4287-a4b6-f1eca4c36ca3': {
        'chunk-i000.thread-i000.link-andMore.shame': `link-andMore-308`,
          'chunk-i000.thread-i000.link-andMore.title': `...и еще одно новое сообщение`,
          'chunk-i000.thread-i000.link-topic.shame': `link-threadTopic-308`,
          'chunk-i000.thread-i000.link-topic.title': `В пустом зале заседаний. Студент. Канцелярии`,
          'chunk-i000.thread-i000.message-i000.message': `И еще немного... Чтобы  убедить  его,  женщина  отворила  дверь  в соседнее помещение.`,
          'chunk-i000.thread-i000.message-i000.newLabel': `Новое`,
          'chunk-i000.thread-i000.message-i000.timestamp': `17/05/2014 02:36:02`,
          'chunk-i000.thread-i000.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i000.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i000.message-i000.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.thread-i000.message-i001.message': `Еще хотел бы добавить вот что.\n\n- Сегодня заседания нет, - сказала женщина.\n- Как это - нет заседания? - спросил он, не поверив.`,
          'chunk-i000.thread-i000.message-i001.newLabel': `Новое`,
          'chunk-i000.thread-i000.message-i001.timestamp': `17/05/2014 02:35:27`,
          'chunk-i000.thread-i000.message-i001.to': `В рельсу`,
          'chunk-i000.thread-i000.message-i001.userLabel-from.icon': `pencil`,
          'chunk-i000.thread-i000.message-i001.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.thread-i001.link-topic.shame': `link-threadTopic-12`,
          'chunk-i000.thread-i001.link-topic.title': `И это называется следственной документацией!`,
          'chunk-i000.thread-i001.message-i000.message': `Нужно было бы еще многое вам сказать. Пришлось изложить только вкратце. Но я надеюсь, что вы меня поняли.`,
          'chunk-i000.thread-i001.message-i000.newLabel': `Новое`,
          'chunk-i000.thread-i001.message-i000.timestamp': `10/04/2014 16:44:55`,
          'chunk-i000.thread-i001.message-i000.to': `В рельсу`,
          'chunk-i000.thread-i001.message-i000.userLabel-from.icon': `user`,
          'chunk-i000.thread-i001.message-i000.userLabel-from.title': `Люк Хуюк`,
          'pageHeader.title': `Поддержка`,
          'tab-main-i000.active': true,
          'tab-main-i000.shame': `updated`,
          'tab-main-i000.title': `Обновленные`,
          'tab-main-i001.shame': `all`,
          'tab-main-i001.title': `Все`,
          'topNavLeft.TopNavItem-i000.badge': `11`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.active': true,
          'topNavLeft.TopNavItem-i001.badge': `4/2`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/support.html`
    }, // end of generated piece of shit

    'b82ede90-f409-4dee-b1d6-e66b56e51152': {
        'Select-ordering.item-i000.title': `Сначала новые`,
          'Select-ordering.item-i000.value': `desc`,
          'Select-ordering.item-i001.title': `Сначала старые`,
          'Select-ordering.item-i001.value': `asc`,
          'Select-ordering.selected.title': `Сначала новые`,
          'Select-ordering.selected.value': `desc`,
          'button-edit.icon': `edit`,
          'button-plus.icon': `comment`,
          'chunk-i000.message-i000.message': `И еще немного... Чтобы  убедить  его,  женщина  отворила  дверь  в соседнее помещение.`,
          'chunk-i000.message-i000.newLabel': `Новое`,
          'chunk-i000.message-i000.timestamp': `17/05/2014 02:36:02`,
          'chunk-i000.message-i000.to': `В рельсу`,
          'chunk-i000.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i000.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i001.message': `Еще хотел бы добавить вот что.\n\n- Сегодня заседания нет, - сказала женщина.\n- Как это - нет заседания? - спросил он, не поверив.`,
          'chunk-i000.message-i001.newLabel': `Новое`,
          'chunk-i000.message-i001.timestamp': `17/05/2014 02:35:27`,
          'chunk-i000.message-i001.to': `В рельсу`,
          'chunk-i000.message-i001.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i001.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i002.message': `Всю следующую неделю К.  изо  дня  в  день  ожидал  нового вызова,  он  не  мог  поверить,  что его отказ от допроса будет принят буквально, а когда ожидаемый вызов до субботы так  и  не пришел, К. усмотрел в этом молчании приглашение в тот же дом на тот  же  час.  Поэтому в воскресенье он снова отправился туда и прямо прошел по этажам и коридорам  наверх;  некоторые  жильцы, запомнившие его, здоровались с ним у дверей, но ему не пришлось никого  спрашивать,  и  он  сам подошел к нужной двери. На стук открыли сразу, и,  не  оглядываясь  на  уже  знакомую  женщину, остановившуюся у дверей, он хотел пройти в следующую комнату.`,
          'chunk-i000.message-i002.newLabel': `Новое`,
          'chunk-i000.message-i002.timestamp': `17/05/2014 02:33:15`,
          'chunk-i000.message-i002.to': `В рельсу`,
          'chunk-i000.message-i002.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i002.userLabel-from.title': `Франц Кафка`,
          'pageHeader.title': `Запрос в поддержку № 308`,
          pageTopBlockQuote: `В пустом зале заседаний. Студент. Канцелярии`,
          'topNavLeft.TopNavItem-i000.badge': `11`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.active': true,
          'topNavLeft.TopNavItem-i001.badge': `4/2`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/support.html?thread=308`
    }, // end of generated piece of shit

    '73952bab-8024-4351-8656-0966860aa31b': {
        'Select-ordering.item-i000.title': `Сначала новые`,
          'Select-ordering.item-i000.value': `desc`,
          'Select-ordering.item-i001.title': `Сначала старые`,
          'Select-ordering.item-i001.value': `asc`,
          'Select-ordering.selected.title': `Сначала старые`,
          'Select-ordering.selected.value': `asc`,
          'button-edit.icon': `edit`,
          'button-plus.icon': `comment`,
          'chunk-i000.message-i000.message': `Всю следующую неделю К.  изо  дня  в  день  ожидал  нового вызова,  он  не  мог  поверить,  что его отказ от допроса будет принят буквально, а когда ожидаемый вызов до субботы так  и  не пришел, К. усмотрел в этом молчании приглашение в тот же дом на тот  же  час.  Поэтому в воскресенье он снова отправился туда и прямо прошел по этажам и коридорам  наверх;  некоторые  жильцы, запомнившие его, здоровались с ним у дверей, но ему не пришлось никого  спрашивать,  и  он  сам подошел к нужной двери. На стук открыли сразу, и,  не  оглядываясь  на  уже  знакомую  женщину, остановившуюся у дверей, он хотел пройти в следующую комнату.`,
          'chunk-i000.message-i000.newLabel': `Новое`,
          'chunk-i000.message-i000.timestamp': `17/05/2014 02:33:15`,
          'chunk-i000.message-i000.to': `В рельсу`,
          'chunk-i000.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i000.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i001.message': `Еще хотел бы добавить вот что.\n\n- Сегодня заседания нет, - сказала женщина.\n- Как это - нет заседания? - спросил он, не поверив.`,
          'chunk-i000.message-i001.newLabel': `Новое`,
          'chunk-i000.message-i001.timestamp': `17/05/2014 02:35:27`,
          'chunk-i000.message-i001.to': `В рельсу`,
          'chunk-i000.message-i001.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i001.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i002.message': `И еще немного... Чтобы  убедить  его,  женщина  отворила  дверь  в соседнее помещение.`,
          'chunk-i000.message-i002.newLabel': `Новое`,
          'chunk-i000.message-i002.timestamp': `17/05/2014 02:36:02`,
          'chunk-i000.message-i002.to': `В рельсу`,
          'chunk-i000.message-i002.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i002.userLabel-from.title': `Франц Кафка`,
          'pageHeader.title': `Запрос в поддержку № 308`,
          pageTopBlockQuote: `В пустом зале заседаний. Студент. Канцелярии`,
          'topNavLeft.TopNavItem-i000.badge': `11`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.active': true,
          'topNavLeft.TopNavItem-i001.badge': `4/2`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/support.html?thread=308&ordering=asc`
    }, // end of generated piece of shit

    '1920f57c-db76-40ff-9f85-8ebdd8faf2f3': {
        'Select-ordering.item-i000.title': `Сначала новые`,
          'Select-ordering.item-i000.value': `desc`,
          'Select-ordering.item-i001.title': `Сначала старые`,
          'Select-ordering.item-i001.value': `asc`,
          'Select-ordering.selected.title': `Сначала новые`,
          'Select-ordering.selected.value': `desc`,
          'button-edit.icon': `edit`,
          'button-plus.icon': `comment`,
          'chunk-i000.message-i000.message': `И еще немного... Чтобы  убедить  его,  женщина  отворила  дверь  в соседнее помещение.`,
          'chunk-i000.message-i000.newLabel': `Новое`,
          'chunk-i000.message-i000.timestamp': `17/05/2014 02:36:02`,
          'chunk-i000.message-i000.to': `В рельсу`,
          'chunk-i000.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i000.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i001.message': `Еще хотел бы добавить вот что.\n\n- Сегодня заседания нет, - сказала женщина.\n- Как это - нет заседания? - спросил он, не поверив.`,
          'chunk-i000.message-i001.newLabel': `Новое`,
          'chunk-i000.message-i001.timestamp': `17/05/2014 02:35:27`,
          'chunk-i000.message-i001.to': `В рельсу`,
          'chunk-i000.message-i001.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i001.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i002.message': `Всю следующую неделю К.  изо  дня  в  день  ожидал  нового вызова,  он  не  мог  поверить,  что его отказ от допроса будет принят буквально, а когда ожидаемый вызов до субботы так  и  не пришел, К. усмотрел в этом молчании приглашение в тот же дом на тот  же  час.  Поэтому в воскресенье он снова отправился туда и прямо прошел по этажам и коридорам  наверх;  некоторые  жильцы, запомнившие его, здоровались с ним у дверей, но ему не пришлось никого  спрашивать,  и  он  сам подошел к нужной двери. На стук открыли сразу, и,  не  оглядываясь  на  уже  знакомую  женщину, остановившуюся у дверей, он хотел пройти в следующую комнату.`,
          'chunk-i000.message-i002.newLabel': `Новое`,
          'chunk-i000.message-i002.timestamp': `17/05/2014 02:33:15`,
          'chunk-i000.message-i002.to': `В рельсу`,
          'chunk-i000.message-i002.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i002.userLabel-from.title': `Франц Кафка`,
          'pageHeader.title': `Запрос в поддержку № 308`,
          pageTopBlockQuote: `В пустом зале заседаний. Студент. Канцелярии`,
          'topNavLeft.TopNavItem-i000.badge': `11`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.active': true,
          'topNavLeft.TopNavItem-i001.badge': `4/2`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/support.html?thread=308&ordering=desc`
    }, // end of generated piece of shit

    'bd47917a-b212-4d03-8910-5af36b2f7ebc': {
        'Input-message': ``,
          'button-primary.title': `Запостить`,
          'chunk-i000.message-i000.message': `И еще немного... Чтобы  убедить  его,  женщина  отворила  дверь  в соседнее помещение.`,
          'chunk-i000.message-i000.newLabel': `Новое`,
          'chunk-i000.message-i000.timestamp': `17/05/2014 02:36:02`,
          'chunk-i000.message-i000.to': `В рельсу`,
          'chunk-i000.message-i000.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i000.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i001.message': `Еще хотел бы добавить вот что.\n\n- Сегодня заседания нет, - сказала женщина.\n- Как это - нет заседания? - спросил он, не поверив.`,
          'chunk-i000.message-i001.newLabel': `Новое`,
          'chunk-i000.message-i001.timestamp': `17/05/2014 02:35:27`,
          'chunk-i000.message-i001.to': `В рельсу`,
          'chunk-i000.message-i001.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i001.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i002.message': `Всю следующую неделю К.  изо  дня  в  день  ожидал  нового вызова,  он  не  мог  поверить,  что его отказ от допроса будет принят буквально, а когда ожидаемый вызов до субботы так  и  не пришел, К. усмотрел в этом молчании приглашение в тот же дом на тот  же  час.  Поэтому в воскресенье он снова отправился туда и прямо прошел по этажам и коридорам  наверх;  некоторые  жильцы, запомнившие его, здоровались с ним у дверей, но ему не пришлось никого  спрашивать,  и  он  сам подошел к нужной двери. На стук открыли сразу, и,  не  оглядываясь  на  уже  знакомую  женщину, остановившуюся у дверей, он хотел пройти в следующую комнату.`,
          'chunk-i000.message-i002.newLabel': `Новое`,
          'chunk-i000.message-i002.timestamp': `17/05/2014 02:33:15`,
          'chunk-i000.message-i002.to': `В рельсу`,
          'chunk-i000.message-i002.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i002.userLabel-from.title': `Франц Кафка`,
          'pageHeader.title': `Запрос в поддержку № 308`,
          pageTopBlockQuote: `В пустом зале заседаний. Студент. Канцелярии`,
          'topNavLeft.TopNavItem-i000.badge': `11`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.active': true,
          'topNavLeft.TopNavItem-i001.badge': `4/2`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/support.html?thread=308&ordering=desc`
    }, // end of generated piece of shit

    '0bb446ca-4e6e-4bcf-b9c9-687f1f3a2f29': {
        'Select-ordering.item-i000.title': `Сначала новые`,
          'Select-ordering.item-i000.value': `desc`,
          'Select-ordering.item-i001.title': `Сначала старые`,
          'Select-ordering.item-i001.value': `asc`,
          'Select-ordering.selected.title': `Сначала новые`,
          'Select-ordering.selected.value': `desc`,
          'button-edit.icon': `edit`,
          'button-plus.icon': `comment`,
          'chunk-i000.message-i000.message': `Та я понял, что ты писатель... В чем дело-то?`,
          'chunk-i000.message-i000.timestamp': `23/07/2016 16:56:26`,
          'chunk-i000.message-i000.userLabel-from.icon': `cog`,
          'chunk-i000.message-i000.userLabel-from.title': `Тодд Суппортод`,
          'chunk-i000.message-i000.userLabel-to.icon': `pencil`,
          'chunk-i000.message-i000.userLabel-to.title': `Франц Кафка`,
          'chunk-i000.message-i001.message': `И еще немного... Чтобы  убедить  его,  женщина  отворила  дверь  в соседнее помещение.`,
          'chunk-i000.message-i001.newLabel': `Новое`,
          'chunk-i000.message-i001.timestamp': `17/05/2014 02:36:02`,
          'chunk-i000.message-i001.to': `В рельсу`,
          'chunk-i000.message-i001.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i001.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i002.message': `Еще хотел бы добавить вот что.\n\n- Сегодня заседания нет, - сказала женщина.\n- Как это - нет заседания? - спросил он, не поверив.`,
          'chunk-i000.message-i002.newLabel': `Новое`,
          'chunk-i000.message-i002.timestamp': `17/05/2014 02:35:27`,
          'chunk-i000.message-i002.to': `В рельсу`,
          'chunk-i000.message-i002.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i002.userLabel-from.title': `Франц Кафка`,
          'chunk-i000.message-i003.message': `Всю следующую неделю К.  изо  дня  в  день  ожидал  нового вызова,  он  не  мог  поверить,  что его отказ от допроса будет принят буквально, а когда ожидаемый вызов до субботы так  и  не пришел, К. усмотрел в этом молчании приглашение в тот же дом на тот  же  час.  Поэтому в воскресенье он снова отправился туда и прямо прошел по этажам и коридорам  наверх;  некоторые  жильцы, запомнившие его, здоровались с ним у дверей, но ему не пришлось никого  спрашивать,  и  он  сам подошел к нужной двери. На стук открыли сразу, и,  не  оглядываясь  на  уже  знакомую  женщину, остановившуюся у дверей, он хотел пройти в следующую комнату.`,
          'chunk-i000.message-i003.newLabel': `Новое`,
          'chunk-i000.message-i003.timestamp': `17/05/2014 02:33:15`,
          'chunk-i000.message-i003.to': `В рельсу`,
          'chunk-i000.message-i003.userLabel-from.icon': `pencil`,
          'chunk-i000.message-i003.userLabel-from.title': `Франц Кафка`,
          'pageHeader.title': `Запрос в поддержку № 308`,
          pageTopBlockQuote: `В пустом зале заседаний. Студент. Канцелярии`,
          'topNavLeft.TopNavItem-i000.badge': `11`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-admin-heap`,
          'topNavLeft.TopNavItem-i000.title': `Куча`,
          'topNavLeft.TopNavItem-i001.active': true,
          'topNavLeft.TopNavItem-i001.badge': `1/1`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i001.title': `Поддержка`,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Тодд`,
          url: `http://aps-ua-writer.local:3022/support.html?thread=308`
    }, // end of generated piece of shit

    '2fcf578d-3b0d-4f70-b3a1-7d4d892ecd91': {
        'link-changePassword.title': `Сменить пароль`,
          'link-signOut.title': `Выйти прочь`,
          'pageHeader.title': `Панель`,
          'topNavLeft.TopNavItem-i000.shame': `TopNavItem-orders`,
          'topNavLeft.TopNavItem-i000.title': `Мои заказы`,
          'topNavLeft.TopNavItem-i001.shame': `TopNavItem-store`,
          'topNavLeft.TopNavItem-i001.title': `Аукцион`,
          'topNavLeft.TopNavItem-i002.shame': `TopNavItem-profile`,
          'topNavLeft.TopNavItem-i002.title': `Профиль`,
          'topNavLeft.TopNavItem-i003.badge': `1`,
          'topNavLeft.TopNavItem-i003.shame': `TopNavItem-support`,
          'topNavLeft.TopNavItem-i003.title': `Поддержка`,
          'topNavLeft.prose.TopNavItem-i000.shame': `TopNavItem-why`,
          'topNavLeft.prose.TopNavItem-i000.title': `Почему мы?`,
          'topNavLeft.prose.TopNavItem-i001.shame': `TopNavItem-prices`,
          'topNavLeft.prose.TopNavItem-i001.title': `Цены`,
          'topNavLeft.prose.TopNavItem-i002.shame': `TopNavItem-faq`,
          'topNavLeft.prose.TopNavItem-i002.title': `ЧаВо`,
          'topNavRight.TopNavItem-i000.active': true,
          'topNavRight.TopNavItem-i000.shame': `TopNavItem-dashboard`,
          'topNavRight.TopNavItem-i000.title': `Франц`,
          url: `http://aps-ua-writer.local:3022/dashboard.html`
    }, // end of generated piece of shit

    // place to insert new generated piece of shit

}
